price_fields = [
    'open',
    'close',
    'high',
    'low',
    'volume',
    'money',
    'open||post',
    'close||post',
    'high||post',
    'low||post',
    'volume||post',
    'money||post',
]

fs_fields = {
    'STK_INCOME_STATEMENT': [
        'pub_date', 'start_date', 'end_date', 'total_operating_revenue',
        'operating_revenue', 'total_operating_cost', 'operating_cost',
        'operating_tax_surcharges', 'sale_expense', 'administration_expense',
        'exploration_expense', 'financial_expense', 'asset_impairment_loss',
        'fair_value_variable_income', 'investment_income',
        'invest_income_associates', 'exchange_income',
        'other_items_influenced_income', 'operating_profit', 'subsidy_income',
        'non_operating_revenue', 'non_operating_expense',
        'disposal_loss_non_current_liability', 'other_items_influenced_profit',
        'total_profit', 'income_tax', 'other_items_influenced_net_profit',
        'net_profit', 'np_parent_company_owners', 'minority_profit', 'eps',
        'basic_eps', 'diluted_eps', 'other_composite_income',
        'total_composite_income', 'ci_parent_company_owners',
        'ci_minority_owners', 'interest_income', 'premiums_earned',
        'commission_income', 'interest_expense', 'commission_expense',
        'refunded_premiums', 'net_pay_insurance_claims',
        'withdraw_insurance_contract_reserve', 'policy_dividend_payout',
        'reinsurance_cost', 'non_current_asset_disposed', 'other_earnings'
    ],
    'STK_CASHFLOW_STATEMENT': [
        'pub_date', 'start_date', 'end_date', 'goods_sale_and_service_render_cash',
        'tax_levy_refund', 'subtotal_operate_cash_inflow',
        'goods_and_services_cash_paid', 'staff_behalf_paid', 'tax_payments',
        'subtotal_operate_cash_outflow', 'net_operate_cash_flow',
        'invest_withdrawal_cash', 'invest_proceeds',
        'fix_intan_other_asset_dispo_cash', 'net_cash_deal_subcompany',
        'subtotal_invest_cash_inflow', 'fix_intan_other_asset_acqui_cash',
        'invest_cash_paid', 'impawned_loan_net_increase',
        'net_cash_from_sub_company', 'subtotal_invest_cash_outflow',
        'net_invest_cash_flow', 'cash_from_invest', 'cash_from_borrowing',
        'cash_from_bonds_issue', 'subtotal_finance_cash_inflow',
        'borrowing_repayment', 'dividend_interest_payment',
        'subtotal_finance_cash_outflow', 'net_finance_cash_flow',
        'exchange_rate_change_effect', 'other_reason_effect_cash',
        'cash_equivalent_increase', 'cash_equivalents_at_beginning',
        'cash_and_equivalents_at_end', 'net_profit',
        'assets_depreciation_reserves', 'fixed_assets_depreciation',
        'intangible_assets_amortization', 'defferred_expense_amortization',
        'fix_intan_other_asset_dispo_loss', 'fixed_asset_scrap_loss',
        'fair_value_change_loss', 'financial_cost', 'invest_loss',
        'deffered_tax_asset_decrease', 'deffered_tax_liability_increase',
        'inventory_decrease', 'operate_receivables_decrease',
        'operate_payable_increase', 'others', 'net_operate_cash_flow_indirect',
        'debt_to_capital', 'cbs_expiring_in_one_year',
        'financial_lease_fixed_assets', 'cash_at_end', 'cash_at_beginning',
        'equivalents_at_end', 'equivalents_at_beginning',
        'other_reason_effect_cash_indirect',
        'cash_equivalent_increase_indirect', 'net_deposit_increase',
        'net_borrowing_from_central_bank', 'net_borrowing_from_finance_co',
        'net_original_insurance_cash',
        'net_cash_received_from_reinsurance_business',
        'net_insurer_deposit_investment', 'net_deal_trading_assets',
        'interest_and_commission_cashin', 'net_increase_in_placements',
        'net_buyback', 'net_loan_and_advance_increase',
        'net_deposit_in_cb_and_ib', 'original_compensation_paid',
        'handling_charges_and_commission', 'policy_dividend_cash_paid',
        'cash_from_mino_s_invest_sub', 'proceeds_from_sub_to_mino_s',
        'investment_property_depreciation'
    ],
    'STK_BALANCE_SHEET': [
        'pub_date',
        'start_date',
        'end_date',
        'cash_equivalents',
        'trading_assets',
        'bill_receivable',
        'account_receivable',
        'advance_payment',
        'other_receivable',
        'affiliated_company_receivable',
        'interest_receivable',
        'dividend_receivable',
        'inventories',
        'expendable_biological_asset',
        'non_current_asset_in_one_year',
        'total_current_assets',
        'hold_for_sale_assets',
        'hold_to_maturity_investments',
        'longterm_receivable_account',
        'longterm_equity_invest',
        'investment_property',
        'fixed_assets',
        'constru_in_process',
        'construction_materials',
        'fixed_assets_liquidation',
        'biological_assets',
        'oil_gas_assets',
        'intangible_assets',
        'development_expenditure',
        'good_will',
        'long_deferred_expense',
        'deferred_tax_assets',
        'total_non_current_assets',
        'total_assets',
        'shortterm_loan',
        'trading_liability',
        'notes_payable',
        'accounts_payable',
        'advance_peceipts',
        'salaries_payable',
        'taxs_payable',
        'interest_payable',
        'dividend_payable',
        'other_payable',
        'affiliated_company_payable',
        'non_current_liability_in_one_year',
        'total_current_liability',
        'longterm_loan',
        'bonds_payable',
        'longterm_account_payable',
        'specific_account_payable',
        'estimate_liability',
        'deferred_tax_liability',
        'total_non_current_liability',
        'total_liability',
        'paidin_capital',
        'capital_reserve_fund',
        'specific_reserves',
        'surplus_reserve_fund',
        'treasury_stock',
        'retained_profit',
        'equities_parent_company_owners',
        'minority_interests',
        'foreign_currency_report_conv_diff',
        'irregular_item_adjustment',
        'total_owner_equities',
        'total_sheet_owner_equities',
        'other_comprehensive_income',
        'deferred_earning',
        'settlement_provi',
        'lend_capital',
        'loan_and_advance_current_assets',
        'derivative_financial_asset',
        'insurance_receivables',
        'reinsurance_receivables',
        'reinsurance_contract_reserves_receivable',
        'bought_sellback_assets',
        'hold_sale_asset',
        'loan_and_advance_noncurrent_assets',
        'borrowing_from_centralbank',
        'deposit_in_interbank',
        'borrowing_capital',
        'derivative_financial_liability',
        'sold_buyback_secu_proceeds',
        'commission_payable',
        'reinsurance_payables',
        'insurance_contract_reserves',
        'proxy_secu_proceeds',
        'receivings_from_vicariously_sold_securities',
        'hold_sale_liability',
        'estimate_liability_current',
        'deferred_earning_current',
        'preferred_shares_noncurrent',
        'pepertual_liability_noncurrent',
        'longterm_salaries_payable',
        'other_equity_tools',
        'preferred_shares_equity',
        'pepertual_liability_equity']

}
